### ISSUE TITLE
flock_simulator/Request.h is not being built?

### ISSUE THREAD

**Issue by alessandromorra** [duckietown/duckietown-fplan#10]
in [duckietown-fplan/src/flock_simulator/CMakeLists.txt](https://github.com/duckietown/duckietown-fplan/blob/master/src/flock_simulator/CMakeLists.txt) you are not building Request.msg - Is it deprecated?

```
add_message_files(
  FILES
  FlockState.msg
  FlockCommand.msg
  DuckieState.msg
  DuckieCommand.msg
)
```

It causes a build error in our dependencies when we try to use your flock_simulator/FlockState.h...

**Comment by cyuanli** [comment]
I reset the master branch to a previous state last week, is your branch up to date?

**Comment by alessandromorra** [comment]
nice it works now! thanks
