### ISSUE TITLE
Jumping duckiebots

### ISSUE THREAD

**Issue by lgulich** [duckietown/duckietown-fplan#7]
When running the flock simulator with the flock_simulator.launch file I experience non-continuities with the duckiebot's positions. I have added the position output from the flock_simulator below. Non-continuities are marked with ** and the respective jumping axis

duckie-0: [0.404231, -0.748527], 2.338021
duckie-0: [0.374567, -0.717765], 2.338021
duckie-0: [0.344903, -0.687003], 2.338021
duckie-0: [0.315239, -0.656240], 2.338021
duckie-0: [0.285575, -0.625478], 2.338021
duckie-0: [0.781917, -0.175613], 2.248736
duckie-0: [0.767127, -0.155468], 2.159450
duckie-0: [0.754192, -0.134084], 2.070164
duckie-0: [0.743215, -0.111632], 1.980878
duckie-0: [0.734284, -0.088290], 1.891593
duckie-0: [0.727470, -0.064245], 1.802307
duckie-0: [0.722827, -0.039689], 1.713021 **y
duckie-0: [0.720392, 0.985184], 1.623736
duckie-0: [0.717235, 1.063035], 1.658458
duckie-0: [0.714615, 1.087896], 1.693180
duckie-0: [0.711133, 1.112651], 1.727902
duckie-0: [0.706793, 1.137271], 1.762624
duckie-0: [0.701602, 1.161724], 1.797347
duckie-0: [0.695565, 1.185983], 1.832069
duckie-0: [0.688689, 1.210018], 1.866791
duckie-0: [0.680983, 1.233799], 1.901513
duckie-0: [0.672456, 1.257299], 1.936236
duckie-0: [0.663119, 1.280488], 1.970958
duckie-0: [0.652982, 1.303340], 2.005680
duckie-0: [0.642058, 1.325825], 2.040402
duckie-0: [0.630360, 1.347918], 2.075124
duckie-0: [0.617902, 1.369591], 2.109847
duckie-0: [0.604699, 1.390819], 2.144569
duckie-0: [0.590767, 1.411576], 2.179291
duckie-0: [0.576123, 1.431836], 2.214013
duckie-0: [0.560784, 1.451576], 2.248736
duckie-0: [0.544770, 1.470772], 2.283458
duckie-0: [0.528098, 1.489400], 2.318180
duckie-0: [0.499050, 1.520745], 2.318180
duckie-0: [0.470002, 1.552090], 2.318180 **x&y
duckie-0: [0.778476, 1.828748], 2.228894
duckie-0: [0.764088, 1.849183], 2.139609
duckie-0: [0.751580, 1.870819], 2.050323
duckie-0: [0.741051, 1.893485], 1.961037
duckie-0: [0.732585, 1.916999], 1.871751
duckie-0: [0.726249, 1.941174], 1.782466
duckie-0: [0.722094, 1.965818], 1.693180 **y
duckie-0: [0.720153, 2.990734], 1.603894
duckie-0: [0.720000, 3.033446], 1.570796
duckie-0: [0.720000, 3.076181], 1.570796
duckie-0: [0.720000, 3.118916], 1.570796
duckie-0: [0.720000, 3.161651], 1.570796
duckie-0: [0.720000, 3.204386], 1.570796

**Comment by cyuanli** [comment]
Yes, we're working on it. It's due to the on-rails behavior, it's not fully working yet.

**Comment by cyuanli** [comment]
Should be fixed with latest commit, closing this issue
