### ISSUE TITLE
Commands not accepted

### ISSUE THREAD

**Issue by lgulich** [duckietown/duckietown-fplan#9]
It seems that the commands from the topic `/flock_simulator/commands` are not processed by the simulator. I could track down the issue to the following if statement:

https://github.com/duckietown/duckietown-fplan/blob/517e02dfa1c878f5529e863184686639dadd02cf/src/flock_simulator/src/state_manager.py#L31

I think it only looks for the `duckie-id` in the dictionary's keys, rather than its values.

**Comment by cyuanli** [comment]
Latest commit should have fixed it, pls try it out

**Comment by lgulich** [comment]
Works like a charm! Thanks! Closing issue
